### ISSUE TITLE
Why not using official Cassandra image ?

### ISSUE THREAD

**Issue by deimosfr** [k8s-for-greeks/docker-cassandra-k8s#15]
Hi,

I was wondering why not using the official Cassandra image instead of fully building one ?

Thanks

**Comment by chrislovecnm** [comment]
The last time I checked the official image had some challenges. But that was awhile ago.

**Comment by chrislovecnm** [comment]
@deimosfr where is it?

**Comment by slavaaaaaaaaaa** [comment]
https://hub.docker.com/_/cassandra/ here it is

**Comment by chrislovecnm** [comment]
So here is the deal. The script that is contained in this image allows from much more fine grain control or C* and how it interacts with k8s 🤷‍♂️.
